### ISSUE TITLE
bf4 datadef ? 

### ISSUE THREAD

**Issue by bigworld12** [SeriousM/gamer_stats#1]
hey man , do you intend to post bf4.datadef ? the bf3 one was way helpful to me ^^

**Comment by SeriousM** [comment]
Hi!
well, I just extracted the data definition from bf3stats.com.
since I'm not working in this tool anymore, you can do that yourself:

http://api.bf4stats.com/api/playerInfo?plat=pc&name=SeriousM
description: http://bf4stats.com/api

cheers!

**Comment by bigworld12** [comment]
i can't seem to find a way to get the variable names ,it only gives me values , so if you can help me please :)

**Comment by bigworld12** [comment]
for examble : 
skill: 120
path = stats.skill
value = 120
it doesn't return the variable

**Comment by SeriousM** [comment]
Ah, here you go:
http://api.bf4stats.com/api/playerInfo?plat=pc&name=1ApRiL&output=js
Just add the output parameter and you get the names as well.

**Comment by bigworld12** [comment]
what i meant is : stat.c_pM1911L__kwa_g , i need to get this variable

**Comment by SeriousM** [comment]
ok, search for "m1911" on http://api.bf4stats.com/api/playerInfo?plat=pc&name=1ApRiL&output=js and you will find a bunch of stats about this weapon and how the player performed with it.
It seems that the format for bf4 is much cleaner than for bf3.

can you see the stats?

**Comment by bigworld12** [comment]
i see numeric stats but no variables

**Comment by SeriousM** [comment]
I don't know what you expect to see! I see variables with values:

![image](https://cloud.githubusercontent.com/assets/462013/10717667/4fe9e5a6-7b5f-11e5-9d11-fdc8ff2711b8.png)

**Comment by bigworld12** [comment]
that's a value not a variable, what i mean is like this
http://puu.sh/kXqEd/1387f4b948.jpeg

**Comment by bigworld12** [comment]
we built our own bf4 master server, and master sends variables like this,
so we need to get what they mean to show the user their stats

**Comment by SeriousM** [comment]
Ah, I see what you up to. I'm sorry, but a detailed search for a bf4 definition was not successful.
The only thing I was able to find was a parser for server settings and games: https://raw.githubusercontent.com/Dwarfer/big-brother-bot/release-1.10/b3/parsers/bf4.py

sorry, but the format from bf4stats is more coder-friendly but less useful for server-admins.
